### ISSUE TITLE
Simplified Representation drops `type`

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#474]
Scorpio 4.1.10  using this [context.jsonld](https://raw.githubusercontent.com/FIWARE/tutorials.Getting-Started/NGSI-LD/data-models/ngsi-context.jsonld).

I have the following **normalized** entity:

```json
{
  "id": "urn:ngsi-ld:Building:farm001",
  "type": "Building",
  "address": {
    "type": "Property",
    "value": {
      "addressLocality": "Tiergarten",
      "addressRegion": "Berlin",
      "postalCode": "10557",
      "streetAddress": "Großer Stern 1"
    },
    "verified": {
      "type": "Property",
      "value": true
    }
  },
  "name": {
    "type": "Property",
    "value": "Victory Farm"
  },
  "location": {
    "type": "GeoProperty",
    "value": {
      "type": "Point",
      "coordinates": [
        13.3505,
        52.5144
      ]
    }
  },
  "category": {
    "type": "Property",
    "value": "farm"
  },
  "@context": [
    "http://context/ngsi-context.jsonld",
    "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.7.jsonld"
  ]
```

I make a request for **simplified** format as shown:

```console
curl -L 'http://localhost:1026/ngsi-ld/v1/entities/urn:ngsi-ld:Building:farm001/?options=simplified' \
-H 'Link: <http://context/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-H 'Accept: application/ld+json'
```

I receive the following:

```json
{
    "id": "urn:ngsi-ld:Building:farm001",
    "address": {
        "addressLocality": "Tiergarten",
        "addressRegion": "Berlin",
        "postalCode": "10557",
        "streetAddress": "Großer Stern 1"
    },
    "name": "Victory Farm",
    "location": {
        "type": "Point",
        "coordinates": [
            13.3505,
            52.5144
        ]
    },
    "category": "farm",
    "@context": [
        "http://context/ngsi-context.jsonld",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.7.jsonld"
    ]
}
```

`type` is missing from the response.

According to the ETSI specification pages 256 et seq. `type` should be included in the simplified response

**Comment by vivekNEC** [comment]
Hi, 
this bug has already been fixed in https://github.com/ScorpioBroker/ScorpioBroker/tree/testsuite-bugfixes and will be merge soon.
Thanks

**Comment by jason-fox** [comment]
Still an open issue with SCORPIO_VERSION=4.1.11

**Comment by jason-fox** [comment]
@vivekNEC - the issue is only partially fixed. There are four ways to specify the key-values format:

- `options=keyValues` ❌  - **Not Fixed**  `type` is missing.
- `options=simplified`  ❌  - **Not Fixed**  `type` is missing.
- `format=keyValues`  ✅  - **Fixed**  `type` is displayed.
- `format=simplified` ✅   - **Fixed**  `type` is displayed.

The `format` may be preferred, but the older `options` parameter should still be properly supported.

**Comment by jason-fox** [comment]
Fixed 4.1.15
