### ISSUE TITLE
Using the aggregation methods min and max on the temporal interface return a string instead of a number

### ISSUE THREAD

**Issue by alifrugal** [ScorpioBroker/ScorpioBroker#524]
When using the temporal interface with the aggregation methods min or max, the broker returns a string instead of a number. 

(Also the attribute `deletedAt`is part of the response.)

For example with `min`: 

```json
{
    "id": "urn:ngsi-ld:Room:Office-1-Room-001",
    "type": [ "Room"],
    "temperature": {
        "type": "Property",
        "max": [
            [
                "18",
                "2023-11-05T07:00:00.000000Z",
                "2023-11-05T09:00:00.000000Z"
            ]
        ]
    },
    "deletedAt": "2024-02-02T15:51:15.000000Z",
    "scope": "/Building/Office-1/Room/Office-1-Room-001"
}
```

The `avg` and `stddev` returns a number as expected: 

```json
{
    "id": "urn:ngsi-ld:Room:Office-1-Room-001",
    "type": [ "Room"],
    "temperature": {
        "type": "Property",
        "avg": [
            [
                17.25,
                "2023-11-05T07:00:00.000000Z",
                "2023-11-05T09:00:00.000000Z"
            ]
        ]
    },
    "deletedAt": "2024-02-02T15:51:15.000000Z",
    "scope": "/Building/Office-1/Room/Office-1-Room-001"
}
```

**Comment by amitrnec** [comment]
Hi,
We are unable to reproduce this error. Could you please share the Scorpio Broker version and steps you are following?

Thanks.

**Comment by martin-p-bauer** [comment]
I had discussed the error with Benjamin a few days ago, before the issue was raised, and it may already be fixed in the latest release. Please check again, but keep this in mind.

**Comment by alifrugal** [comment]
@martin-p-bauer  I just tried with version `4.1.14` and I still see the issue: 

```
{
    "id": "urn:ngsi-ld:Room:Office-1-Room-001",
    "type": [
        "Room",
        "MeetingRoom"
    ],
    "temperature": {
        "type": "Property",
        "min": [
            [
                "16",
                "2023-11-05T07:00:00.000000Z",
                "2023-11-05T09:00:00.000000Z"
            ]
        ]
    },
    "scope": "/Building/Office-1/Room/Office-1-Room-001"
}
```

@amitrnec, I updated this entity multiple times using the query (just changing the value of `temperature` and `observedAt`

```
curl --location '{BrokerEndpoint}/ngsi-ld/v1/entities/urn:ngsi-ld:Room:Office-1-Room-001/attrs' \
--header 'Link: <https://raw.githubusercontent.com/awslabs/garnet-framework/main/context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--header 'Content-Type: application/json' \
--data '{ 
  "temperature": {
    "value": 18,
    "observedAt": "2023-11-05T07:00:00.000Z",
    "unitCode": "CEL",
    "providedBy": {
        "object": "urn:ngsi-ld:Thing:TemperatureSensor-001"
    }
  }
}' 
```


Then querying the temporal interface using 

```
curl --location '{BrokerEndpoint}/ngsi-ld/v1/temporal/entities/urn:ngsi-ld:Room:Office-1-Room-001?attrs=temperature&aggrMethods=min' \
--header 'Link: <https://raw.githubusercontent.com/awslabs/garnet-framework/main/context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"'
```
