### ISSUE TITLE
`Content-Type` header is misspelt `contenttype` within a notification

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#581]
Scorpio 4.1.15. Related #510

When raising a notification without `receiverInfo` the following headers are returned:

```json
{
   "user-agent": "Vert.x-WebClient/4.4.4",
   "ngsild-tenant": "openiot",
   "link": "<http://context/user-context.jsonld>; rel=\"http://www.w3.org/ns/json-ld#context\"; type=\"application/ld+json\"",
   "accept": "application/json",
   "contenttype": "application/json",
   "content-length": "1625",
   "host": "tutorial:3000"
 }
 ```

This is **Incorrect** - the [`content-type` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) is missing the hyphen and will not be recognised.

**Comment by vivekNEC** [comment]
Hi @jason-fox,

This issue has already been fixed in https://github.com/ScorpioBroker/ScorpioBroker/commit/ec6c9f672de920cd2ee973fc8185029d7e66853e . Please wait for the next release.

Thanks

**Comment by ScorpioBroker** [comment]
Fixed in 5.0.0

**Comment by jason-fox** [comment]
@ScorpioBroker - I have retested this with Scorpio 5.0.0, and this is still not fixed. The received headers are now:

```json
{
 "user-agent": "Vert.x-WebClient/4.4.4",
  "accept": "application/json",
  "content-length": "1625",
  "host": "tutorial:3000"
}
```

- The `link` header is not present.
- The `content-type` header  is not present.
- The `ngsild-tenant` is not present.

**Comment by ScorpioBroker** [comment]
hmmm can't confirm in the test @jason-fox  do you have an example at hand?

https://productionresultssa11.blob.core.windows.net/actions-results/de65a37f-7112-46fa-8a79-17d40ae10404/workflow-job-run-30bb9202-5a5f-5a22-170a-64093fed97ed/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-09-03T14%3A47%3A33Z&sig=60%2FBitYJZErpWhfjpQLuvpV2sC4ZVKsmyvcI3QkrUzo%3D&ske=2024-09-04T01%3A54%3A59Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-09-03T13%3A54%3A59Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-09-03T14%3A37%3A28Z&sv=2024-05-04
basically all the testserver-1 outputs look like this 

2024-09-01T15:40:59.5574244Z scorpio-1     | [39m[38;5;227m
2024-09-01T15:40:59.5576441Z testserver-1  | {"id": "notification:-8008205134889139981", "type": "Notification", "subscriptionId": "urn:ngsi-ld:Subscription:mytest1", "notifiedAt": "2024-09-01T15:35:51.784000Z", "data": [{"id": "urn:test:testentity1", "type": "TestType", "complexproperty": {"type": "Property", "value": {"some": {"more": "values"}}}, "floatproperty": {"type": "Property", "value": 123.456}, "intproperty": {"type": "Property", "value": 123}, "stringproperty": {"type": "Property", "value": "teststring"}, "testrelationship": {"type": "Relationship", "object": "urn:testref1"}}]}
2024-09-01T15:40:59.5576656Z testserver-1  | user-agent: Vert.x-WebClient/4.4.4
2024-09-01T15:40:59.5577401Z testserver-1  | Link: <https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.7.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"
2024-09-01T15:40:59.5577573Z testserver-1  | Accept: application/json
2024-09-01T15:40:59.5577756Z testserver-1  | Content-Type: application/json
2024-09-01T15:40:59.5577910Z testserver-1  | content-length: 747
2024-09-01T15:40:59.5578062Z testserver-1  | host: testserver:8080
2024-09-01T15:40:59.5578175Z testserver-1  | 
2024-09-01T15:40:59.5578291Z testserver-1  | 
2024-09-01T15:40:59.5578436Z testserver-1  | -----------------------
2024-09-01T15:40:59.5583713Z testserver-1  | {"id": "notification:-4801793272959720098", "type": "Notification", "subscriptionId": "urn:ngsi-ld:Subscription:mytestgeoresponse", "notifiedAt": "2024-09-01T15:35:54.864000Z", "data": {"type": "FeatureCollection", "features": [{"id": "urn:test:testentity1", "type": "Feature", "geometry": {"type": "Point", "coordinates": [40, 40]}, "properties": {"type": "TestType", "complexproperty": {"type": "Property", "value": {"some": {"more": "values"}}}, "floatproperty": {"type": "Property", "value": 123.456}, "intproperty": {"type": "Property", "value": 123}, "listproperty": {"type": "ListProperty", "valueList": [100, 200, 300]}, "passenger": {"type": "ListRelationship", "objectList": [{"object": "urn:ngsi-ld:Person:Alice"}, {"object": "urn:ngsi-ld:Person:Bob"}], "objectType": "Person"}, "street": {"type": "LanguageProperty", "languageMap": {"fr": "Grand Place", "nl": "Grote Markt"}}, "stringproperty": {"type": "Property", "value": "teststring"}, "testjsonproperty": {"type": "JsonProperty", "json": {"id": "85a6cc52-0589-45f9", "value": "Overstay 60 minutes"}}, "testrelationship": {"type": "Relationship", "object": "urn:testref1"}, "vocabproperty": {"type": "VocabProperty", "vocab": "x"}, "location": {"type": "GeoProperty", "value": {"type": "Point", "coordinates": [40, 40]}}}}], "@context": ["https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.8.jsonld"]}}
2024-09-01T15:40:59.5583931Z testserver-1  | user-agent: Vert.x-WebClient/4.4.4
2024-09-01T15:40:59.5584108Z testserver-1  | Accept: application/geo+json
2024-09-01T15:40:59.5584306Z testserver-1  | Content-Type: application/geo+json
2024-09-01T15:40:59.5584454Z testserver-1  | content-length: 2178
2024-09-01T15:40:59.5584611Z testserver-1  | host: testserver:8080
2024-09-01T15:40:59.5584730Z testserver-1  | 
2024-09-01T15:40:59.5584843Z testserver-1  | 
2024-09-01T15:40:59.5584992Z testserver-1  | -----------------------
2024-09-01T15:40:59.5587332Z testserver-1  | {"id": "notification:-6323811261381583589", "type": "Notification", "subscriptionId": "urn:ngsi-ld:Subscription:mytest1888", "notifiedAt": "2024-09-01T15:36:00.968000Z", "data": [{"id": "myprefixurn:test:testentity2", "type": "TestType2", "complexproperty": {"type": "Property", "value": {"some": {"more": "values"}}}, "floatproperty": {"type": "Property", "value": 123.456}, "intproperty": {"type": "Property", "value": 123}, "stringproperty": {"type": "Property", "value": "teststring"}, "testrelationship": {"type": "Relationship", "object": "urn:testref1"}}]}

or with a tenant 

2024-09-01T15:40:59.7708818Z testserver-1  | user-agent: Vert.x-WebClient/4.4.4
2024-09-01T15:40:59.7708984Z testserver-1  | NGSILD-Tenant: testtenant
2024-09-01T15:40:59.7709740Z testserver-1  | Link: <https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.7.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"
2024-09-01T15:40:59.7709900Z testserver-1  | Accept: application/json
2024-09-01T15:40:59.7710080Z testserver-1  | Content-Type: application/json
2024-09-01T15:40:59.7710236Z testserver-1  | content-length: 11485
2024-09-01T15:40:59.7710383Z testserver-1  | host: testserver:8080

**Comment by jason-fox** [comment]
I've retested - it looks like it was my fault - user error. The test was still using 4.1.15 instead of the updated 5.0.0
